authorName: default
experimentName: havsim_dl_hpo
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 120
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
 builtinTunerName: TPE
 classArgs:
   optimize_mode: minimize
assessor:
    builtinAssessorName: Medianstop
    classArgs:
      optimize_mode: minimize
      start_step: 10
trial:
  command: python3 DL2.py
  codeDir: .
  gpuNum: 0
