authorName: default
experimentName: havsim_dl_hpo
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 120
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  builtinAdvisorName: BOHB
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
    min_budget: 5
    max_budget: 38
    eta: 2
    top_n_percent: 15
trial:
  command: python DL2.py
  codeDir: .
  gpuNum: 0